### ISSUE TITLE
Gossip with localhost/127.0.0.1 flooding debug

### ISSUE THREAD

**Issue by cclulu** [orange-cloudfoundry/cassandra-boshrelease#51]
I am using [v6](https://github.com/orange-cloudfoundry/cassandra-boshrelease/releases/tag/v6) to deploy Cassandra to our bosh environment. I deployed an instance using this configuration:
```yaml
---
name: <deploy-name>

releases:
- name: cassandra
  version: "6"

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: <version>

instance_groups:
- name: cassandra-seeds
  azs:
  - z1
  - z2
  instances: 2
  vm_type: <vm-type>
  stemcell: trusty
  networks:
  - name: <name-of-network>
    static_ips:
    - xx.xxx.xxx.225
    - xx.xxx.xxx.226
  persistent_disk: 300_000 #MB
  jobs:
  - name: cassandra
    release: cassandra
    consumes:
      seeds:
        instances:
        - address: xx.xxx.xxx.225
        - address: xx.xxx.xxx.226
        - address: xx.xxx.xxx.225
    properties:
      cass_KSP: <key-store-password>
      cass_pwd: <cassandra-password
      cluster_name: <cluster-name>
      listen_address: ['xx.xxx.xxx.225', 'xx.xxx.xxx.226']
      max_heap_size: 8G
      heap_newsize: 800M
      topology:
        - xx.xxx.xxx.225=DC1:RAC1
        - xx.xxx.xxx.226=DC1:RAC1
        - xx.xxx.xxx.225=DC2:RAC1

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
```
the config to the third instance is the same but rather than 2 it is just one. We can get the database to talk with each other, but when looking at the `debug.log` file it is flooded with the following message:

```java
DEBUG [MessagingService-Outgoing-localhost/127.0.0.1-Gossip] 2018-06-07 16:04:39,921 OutboundTcpConnection.java:545 - Unable to connect to localhost/127.0.0.1
java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_102-ea]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_102-ea]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_102-ea]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_102-ea]
	at org.apache.cassandra.net.OutboundTcpConnectionPool.newSocket(OutboundTcpConnectionPool.java:146) ~[apache-cassandra-3.11.1.jar:3.11.1]
	at org.apache.cassandra.net.OutboundTcpConnectionPool.newSocket(OutboundTcpConnectionPool.java:132) ~[apache-cassandra-3.11.1.jar:3.11.1]
	at org.apache.cassandra.net.OutboundTcpConnection.connect(OutboundTcpConnection.java:433) [apache-cassandra-3.11.1.jar:3.11.1]
	at org.apache.cassandra.net.OutboundTcpConnection.run(OutboundTcpConnection.java:262) [apache-cassandra-3.11.1.jar:3.11.1]
```

We change the `listen_address` in hopes that this would tell cassandra where to gossip, but it still seems to communicate with localhost, I am not sure if this is an issue with the release, or if my configuration and understanding is just wrong.

I should note that we have also deployed it without even using the `listen_address` to start, and changed it to use the `listen_address` to fix the error to no avail.

**Comment by cclulu** [comment]
So I have managed to find out what caused of it was. It seem the line:
```yaml
- seeds: <% link('seeds').instances.each do |instance| %><%= instance.address %>,<% end %>
```
would leave a trailing comma, which set localhost as a seed and so it started gossiping with localhost, which then printed out the error constantly. It seem like it will be fixed for the next release since it looks like [this](https://github.com/orange-cloudfoundry/cassandra-boshrelease/commit/6eb9c423affef3f1f9126e1e7ddcb8d0dedc8131#diff-74641ca87451980d36be25ab06678560R428) commit will have fixed it.  I will close this issue.
